name: scripts

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.6.0
  dexeca: ^1.0.1
  dexecve: ^1.1.0
  ini: ^2.0.1
  path: ^1.7.0
  prompts: ^1.3.1
  uuid: ^2.0.4
  utf: ^0.9.0+5

dev_dependencies:
  pedantic: ^1.8.0
