on:
  push:
    branches:
      - master

env:
  CI: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VCN_EMAIL: ${{ secrets.VCN_EMAIL }}
      VCN_PASSWORD: ${{ secrets.VCN_PASSWORD }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Read .go-version
        run: echo ::set-output name=GO_VERSION::$(cat .go-version | xargs)
        id: gvm
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ steps.gvm.outputs.GO_VERSION }}
      - name: Read .node-version
        run: echo ::set-output name=NODE_VERSION::$(cat .node-version | xargs)
        id: nvm
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Restore go cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
      - name: Restore node cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm ci
      - run: npx semantic-release
